/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f1",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-fixed": "#001f24",
        "on-tertiary-container": "#f04244",
        "primary-container": "#1b1b1b",
        "tertiary-container": "#410004",
        "surface-variant": "#e2e2e2",
        "secondary-fixed": "#9cf0ff",
        "on-primary-container": "#848484",
        "background": "#f9f9f9",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-error": "#ffffff",
        "secondary": "#006875",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#004f58",
        "outline": "#7e7576",
        "tertiary-fixed-dim": "#ffb3ae",
        "secondary-fixed-dim": "#00daf3",
        "outline-variant": "#cfc4c5",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-primary": "#c6c6c6",
        "primary-fixed": "#e2e2e2",
        "on-surface-variant": "#4c4546",
        "primary": "#000000",
        "surface-dim": "#dadada",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed": "#410004",
        "surface": "#f9f9f9",
        "on-secondary": "#ffffff",
        "surface-container": "#eeeeee",
        "on-secondary-container": "#00616d",
        "on-tertiary-fixed-variant": "#930014",
        "inverse-surface": "#2f3131",
        "on-surface": "#1a1c1c",
        "surface-container-low": "#f3f3f4",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "surface-tint": "#5e5e5e",
        "on-background": "#1a1c1c",
        "surface-bright": "#f9f9f9",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdad7",
        "on-error-container": "#93000a",
        "secondary-container": "#00e3fd",
        "border": "#000000",
        "input": "#000000",
        "ring": "#000000"
      },
      borderWidth: {
        "border-width": "4px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "offset-depth": "6px",
        "border-width": "4px",
        "container-margin": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "headline-xl": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "data-mono": ["JetBrains Mono"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
